#!/bin/bash

killall wbar
killall tint2
killall openbox-menu

# blank root window to show openbox isn't running
hsetroot





# if we're switching to another GUI rather than just restarting
#if ! grep "openbox-pandora-session" /tmp/gui.load > /dev/null
#then
	# save our gtkrc
#	cp $HOME/.gtkrc-2.0 $XDG_CONFIG_HOME/openbox/gtkrc

	# delete ON/OFF values for usb, bluetooth and wifi
#	rm $XDG_CACHE_HOME/usb $XDG_CACHE_HOME/bluetooth $XDG_CACHE_HOME/wifi 	

	# give XFCE / MiniMenu their cache directory back
	export XDG_CACHE_HOME=$OPENBOX_OLD_CACHEDIR

	# give XFCE / MiniMenu their GTK+ theme back
#	cp $HOME/.gtkrc-2.0_xfwm4 $HOME/.gtkrc-2.0

	# bluetooth-applet is now in XFCE autostart
	# kill it so there isn't 2 of them
#	killall bluetooth-applet
#fi

openbox --exit
